version: "3"
services:
  mypostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    
  myapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: postgresql://postgres:postgres@mypostgres/employee_management
    depends_on:
      - mypostgres